In [351]:
import numpy as np
import pandas as pd

In [352]:
df = pd.read_csv('final_cleaned_data.csv')

In [353]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [354]:
df.head()

,brand_name,model,price,rating,has_dual_sim,has_5G,has_NFC,has_IR_Blaster,processor_brand,no_of_cores,processor_speed,ram,rom,fast_charging_available,battery_capacity,screen_size,pixels_in_width,pixels_in_height,refresh_rate,no_of_rear_cameras,no_of_front_cameras,primary_front_camera,primary_rear_camera,total_no_of_cameras,extended_memory_available,memory_extended_upto,operating_system
0,xiaomi,Xiaomi Redmi 12 5G,11999,75.0,1,1,0,1,snapdragon,8,2.2,4,128.0,1,5000.0,6.79,1080,2460,90.0,2,1,8.0,50.0,3,1,1024.0,Android v13
1,xiaomi,Xiaomi Redmi 12 5G (6 GB RAM + 128 GB),13499,77.0,1,1,0,1,snapdragon,8,2.2,6,128.0,1,5000.0,6.79,1080,2460,90.0,2,1,8.0,50.0,3,1,1024.0,Android v13
2,xiaomi,Xiaomi Redmi 12 5G (8GB RAM + 256GB),15499,80.0,1,1,0,1,snapdragon,8,2.2,8,256.0,1,5000.0,6.79,1080,2460,90.0,2,1,8.0,50.0,3,1,1024.0,Android v13
3,oneplus,OnePlus Nord CE 3 Lite 5G,19999,85.0,1,1,0,0,snapdragon,8,2.2,8,128.0,1,5000.0,6.72,1080,2400,120.0,3,1,16.0,108.0,4,1,1024.0,Android v13
4,samsung,Samsung Galaxy F34 5G,18999,83.0,1,1,1,0,exynos,8,2.4,6,128.0,1,6000.0,6.50,1080,2340,120.0,3,1,13.0,50.0,4,1,1024.0,Android v13

In [355]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 703 entries, 0 to 702
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 703 non-null    object
 1   model                      703 non-null    object
 2   price                      703 non-null    int64
 3   rating                     633 non-null    float64
 4   has_dual_sim               703 non-null    int64
 5   has_5G                     703 non-null    int64
 6   has_NFC                    703 non-null    int64
 7   has_IR_Blaster             703 non-null    int64
 8   processor_brand            703 non-null    object
 9   no_of_cores                703 non-null    int64
 10  processor_speed            703 non-null    float64
 11  ram                        703 non-null    int64
 12  rom                        703 non-null    float64
 13  fast_charging_available    703 non-null    int64
 14  battery_capacity           703 non-null    float64
 15  screen_size                703 non-null    float64
 16  pixels_in_width            703 non-null    int64
 17  pixels_in_height           703 non-null    int64
 18  refresh_rate               703 non-null    float64
 19  no_of_rear_cameras         703 non-null    int64
 20  no_of_front_cameras        703 non-null    int64
 21  primary_front_camera       703 non-null    float64
 22  primary_rear_camera        703 non-null    float64
 23  total_no_of_cameras        703 non-null    int64
 24  extended_memory_available  703 non-null    int64
 25  memory_extended_upto       703 non-null    float64
 26  operating_system           703 non-null    object
dtypes: float64(9), int64(14), object(4)
memory usage: 148.4+ KB

In [356]:

# to make only two categories:Android,ios
df['operating_system'].value_counts()

Android v12    233
Android v11    174
Android v13    159
Android v10     78
Android v9      15
iOS v15         14
iOS v16         14
Android v8       9
iOS v14          3
iOS v13          2
Android v7       1
Android v5       1
Name: operating_system, dtype: int64

In [357]:
def os(text):
    if 'Android' in text:
        return 'Android'
    else:
        return 'iOS'

In [358]:
df['operating_system'] = df['operating_system'].apply(os)

In [359]:
df['operating_system'].value_counts()

Android    670
iOS         33
Name: operating_system, dtype: int64

In [360]:

# to remove brands with only 1 phone
df['brand_name'].value_counts()

xiaomi       111
samsung      110
realme        89
vivo          54
poco          38
motorola      34
oppo          34
apple         33
tecno         32
ikall         28
infinix       27
oneplus       24
nokia         23
iqoo          20
lava          17
itel          14
google         4
nothing        4
jio            1
asus           1
micromax       1
lyf            1
unihertz       1
blackzone      1
gionee         1
Name: brand_name, dtype: int64

In [361]:
brand_counts = df['brand_name'].value_counts()

# Get a list of brands with more than one occurrence
brands_to_keep = brand_counts[brand_counts > 1].index.tolist()

# Filter the DataFrame to keep only rows with brands in the 'brands_to_keep' list
df = df[df['brand_name'].isin(brands_to_keep)]

In [362]:
df.shape

(696, 27)

In [363]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 696 entries, 0 to 702
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 696 non-null    object
 1   model                      696 non-null    object
 2   price                      696 non-null    int64
 3   rating                     629 non-null    float64
 4   has_dual_sim               696 non-null    int64
 5   has_5G                     696 non-null    int64
 6   has_NFC                    696 non-null    int64
 7   has_IR_Blaster             696 non-null    int64
 8   processor_brand            696 non-null    object
 9   no_of_cores                696 non-null    int64
 10  processor_speed            696 non-null    float64
 11  ram                        696 non-null    int64
 12  rom                        696 non-null    float64
 13  fast_charging_available    696 non-null    int64
 14  battery_capacity           696 non-null    float64
 15  screen_size                696 non-null    float64
 16  pixels_in_width            696 non-null    int64
 17  pixels_in_height           696 non-null    int64
 18  refresh_rate               696 non-null    float64
 19  no_of_rear_cameras         696 non-null    int64
 20  no_of_front_cameras        696 non-null    int64
 21  primary_front_camera       696 non-null    float64
 22  primary_rear_camera        696 non-null    float64
 23  total_no_of_cameras        696 non-null    int64
 24  extended_memory_available  696 non-null    int64
 25  memory_extended_upto       696 non-null    float64
 26  operating_system           696 non-null    object
dtypes: float64(9), int64(14), object(4)
memory usage: 152.2+ KB

In [364]:

# to convert 'pixels_in_width' & 'pixels_in_height' numerical columns into 1 categorical column
df['pixels_in_height'].value_counts().sort_index()

360       2
480       2
720      25
960       5
1014      1
1080     13
1280      2
1334      3
1440      2
1520      7
1560      9
1600    141
1612     23
1640      3
1650      6
1792      2
1920      1
2176      3
2208      1
2220      1
2246      1
2280      1
2296      1
2340     37
2376      5
2388      4
2400    220
2404      3
2408     48
2412     33
2460     24
2520      1
2532     12
2556      4
2640      7
2772      5
2778      6
2796      4
2800      3
3040      1
3080      2
3088      2
3120      1
3168      1
3200     10
3216      8
Name: pixels_in_height, dtype: int64

In [365]:
def resolution(num):
    if num < 720:
        return 'FWVGA'
    elif 1080 > num >= 720:
        return 'HD'
    elif num == 1080:
        return 'Full HD'
    elif 1440 > num > 1080:
        return 'Full HD+'
    elif 2160 > num >= 1440:
        return 'Quad HD'
    else:
        return 'Ultra HD'

In [366]:
resolution = df['pixels_in_height'].apply(resolution)

In [367]:
df.insert(18,'resolution',resolution)

In [368]:
df.head()

,brand_name,model,price,rating,has_dual_sim,has_5G,has_NFC,has_IR_Blaster,processor_brand,no_of_cores,processor_speed,ram,rom,fast_charging_available,battery_capacity,screen_size,pixels_in_width,pixels_in_height,resolution,refresh_rate,no_of_rear_cameras,no_of_front_cameras,primary_front_camera,primary_rear_camera,total_no_of_cameras,extended_memory_available,memory_extended_upto,operating_system
0,xiaomi,Xiaomi Redmi 12 5G,11999,75.0,1,1,0,1,snapdragon,8,2.2,4,128.0,1,5000.0,6.79,1080,2460,Ultra HD,90.0,2,1,8.0,50.0,3,1,1024.0,Android
1,xiaomi,Xiaomi Redmi 12 5G (6 GB RAM + 128 GB),13499,77.0,1,1,0,1,snapdragon,8,2.2,6,128.0,1,5000.0,6.79,1080,2460,Ultra HD,90.0,2,1,8.0,50.0,3,1,1024.0,Android
2,xiaomi,Xiaomi Redmi 12 5G (8GB RAM + 256GB),15499,80.0,1,1,0,1,snapdragon,8,2.2,8,256.0,1,5000.0,6.79,1080,2460,Ultra HD,90.0,2,1,8.0,50.0,3,1,1024.0,Android
3,oneplus,OnePlus Nord CE 3 Lite 5G,19999,85.0,1,1,0,0,snapdragon,8,2.2,8,128.0,1,5000.0,6.72,1080,2400,Ultra HD,120.0,3,1,16.0,108.0,4,1,1024.0,Android
4,samsung,Samsung Galaxy F34 5G,18999,83.0,1,1,1,0,exynos,8,2.4,6,128.0,1,6000.0,6.50,1080,2340,Ultra HD,120.0,3,1,13.0,50.0,4,1,1024.0,Android

In [369]:
df.drop(columns=['pixels_in_width','pixels_in_height'],inplace=True)

In [378]:
df['rom'] = df['rom'].astype(np.int64)

In [379]:
df['battery_capacity'] = df['battery_capacity'].astype(np.int64)

In [380]:
df['refresh_rate'] = df['refresh_rate'].astype(np.int64)

In [381]:
df['primary_rear_camera'] = df['primary_rear_camera'].astype(np.int64)

In [382]:
df['memory_extended_upto'] = df['memory_extended_upto'].astype(np.int64)

In [383]:
df['primary_front_camera'] = df['primary_front_camera'].astype(np.int64)

In [384]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 696 entries, 0 to 702
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 696 non-null    object
 1   model                      696 non-null    object
 2   price                      696 non-null    int64
 3   rating                     696 non-null    float64
 4   has_dual_sim               696 non-null    int64
 5   has_5G                     696 non-null    int64
 6   has_NFC                    696 non-null    int64
 7   has_IR_Blaster             696 non-null    int64
 8   processor_brand            696 non-null    object
 9   no_of_cores                696 non-null    int64
 10  processor_speed            696 non-null    float64
 11  ram                        696 non-null    int64
 12  rom                        696 non-null    int64
 13  fast_charging_available    696 non-null    int64
 14  battery_capacity           696 non-null    int64
 15  screen_size                696 non-null    float64
 16  resolution                 696 non-null    object
 17  refresh_rate               696 non-null    int64
 18  no_of_rear_cameras         696 non-null    int64
 19  no_of_front_cameras        696 non-null    int64
 20  primary_front_camera       696 non-null    int64
 21  primary_rear_camera        696 non-null    int64
 22  total_no_of_cameras        696 non-null    int64
 23  extended_memory_available  696 non-null    int64
 24  memory_extended_upto       696 non-null    int64
 25  operating_system           696 non-null    object
dtypes: float64(3), int64(18), object(5)
memory usage: 146.8+ KB

In [385]:
from sklearn.impute import KNNImputer

imputer = KNNImputer()  # Choose an appropriate value for 'n_neighbors'
df['rating'] = imputer.fit_transform(df[['rating']])

In [386]:
df['rating'].value_counts()

77.408585    67
75.000000    43
82.000000    43
84.000000    40
83.000000    35
85.000000    32
86.000000    30
89.000000    28
79.000000    27
80.000000    27
81.000000    25
87.000000    23
88.000000    23
74.000000    23
61.000000    21
77.000000    21
71.000000    21
66.000000    18
70.000000    17
78.000000    15
65.000000    14
73.000000    12
72.000000    12
64.000000    12
76.000000    12
68.000000    11
69.000000    11
60.000000    11
62.000000    11
67.000000     7
63.000000     4
Name: rating, dtype: int64

In [389]:
df['rating'] = df['rating'].astype(np.int64)

In [390]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 696 entries, 0 to 702
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 696 non-null    object
 1   model                      696 non-null    object
 2   price                      696 non-null    int64
 3   rating                     696 non-null    int64
 4   has_dual_sim               696 non-null    int64
 5   has_5G                     696 non-null    int64
 6   has_NFC                    696 non-null    int64
 7   has_IR_Blaster             696 non-null    int64
 8   processor_brand            696 non-null    object
 9   no_of_cores                696 non-null    int64
 10  processor_speed            696 non-null    float64
 11  ram                        696 non-null    int64
 12  rom                        696 non-null    int64
 13  fast_charging_available    696 non-null    int64
 14  battery_capacity           696 non-null    int64
 15  screen_size                696 non-null    float64
 16  resolution                 696 non-null    object
 17  refresh_rate               696 non-null    int64
 18  no_of_rear_cameras         696 non-null    int64
 19  no_of_front_cameras        696 non-null    int64
 20  primary_front_camera       696 non-null    int64
 21  primary_rear_camera        696 non-null    int64
 22  total_no_of_cameras        696 non-null    int64
 23  extended_memory_available  696 non-null    int64
 24  memory_extended_upto       696 non-null    int64
 25  operating_system           696 non-null    object
dtypes: float64(2), int64(19), object(5)
memory usage: 146.8+ KB

In [391]:
df.drop(columns=['total_no_of_cameras','extended_memory_available'],inplace=True)

In [392]:
df.head()

,brand_name,model,price,rating,has_dual_sim,has_5G,has_NFC,has_IR_Blaster,processor_brand,no_of_cores,processor_speed,ram,rom,fast_charging_available,battery_capacity,screen_size,resolution,refresh_rate,no_of_rear_cameras,no_of_front_cameras,primary_front_camera,primary_rear_camera,memory_extended_upto,operating_system
0,xiaomi,Xiaomi Redmi 12 5G,11999,75,1,1,0,1,snapdragon,8,2.2,4,128,1,5000,6.79,Ultra HD,90,2,1,8,50,1024,Android
1,xiaomi,Xiaomi Redmi 12 5G (6 GB RAM + 128 GB),13499,77,1,1,0,1,snapdragon,8,2.2,6,128,1,5000,6.79,Ultra HD,90,2,1,8,50,1024,Android
2,xiaomi,Xiaomi Redmi 12 5G (8GB RAM + 256GB),15499,80,1,1,0,1,snapdragon,8,2.2,8,256,1,5000,6.79,Ultra HD,90,2,1,8,50,1024,Android
3,oneplus,OnePlus Nord CE 3 Lite 5G,19999,85,1,1,0,0,snapdragon,8,2.2,8,128,1,5000,6.72,Ultra HD,120,3,1,16,108,1024,Android
4,samsung,Samsung Galaxy F34 5G,18999,83,1,1,1,0,exynos,8,2.4,6,128,1,6000,6.50,Ultra HD,120,3,1,13,50,1024,Android

In [393]:
df.to_csv('final_data_for_modelling.csv',index=False)